topics:
-
  name    : navigation
  topic   : cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : joystick
  topic   : cmd_vel_joy
  timeout : 0.5
  priority: 100
-
  name    : tracker
  topic   : cmd_vel_tracker
  timeout : 0.5
  priority: 20